#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "docker-cli-plugin-metadata" ]; then
    echo '{"SchemaVersion":"0.1.0","Vendor":"MyEnv","Version":"1.0.0","ShortDescription":"ここにコマンドの説明を書く"}'
    exit 0
fi

if [ "$#" -gt 0 ]; then
    echo "Hello from docker-hello: $*"
else
    echo "Hello from docker-hello"
fi
exit 0
